Dockerfile

CASMNET-904 - add canu user home dir and workdir to container env

CASMNET-904 - add canu user home dir and workdir to container env

---

network_modeling/models/cray-network-architecture.yaml
network_modeling/models/cray-network-hardware.yaml
readme.md

Signed-off-by: Jacob Salmela <jacob.salmela@hpe.com>

CASMNET-806 add hsn hardware to architecture

---

.github/CODE_OF_CONDUCT.md

Signed-off-by: Jacob Salmela <jacob.salmela@hpe.com>

add code of conduct file

---

canu/generate/switch/config/config.py
network_modeling/models/cray-network-architecture.yaml

Description: 
Add subrack to TDS architecture, and generate config for subracks.
CASMNET-1031

CASMNET-1031 add subrack to TDS arch

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/docs.md
.github/ISSUE_TEMPLATE/rfe.md

Signed-off-by: Jacob Salmela <jacob.salmela@hpe.com>
Adds Issue Templates.
N/A
N/A

add issue templates

---

canu/validate/switch/config/config.py
canu/validate/switch/config/mellanox_tags.yaml
network_modeling/configs/templates/1.2/dellmellanox/full/sw-spine.primary.j2
network_modeling/configs/templates/1.2/dellmellanox/full/sw-spine.secondary.j2
tests/test_generate_switch_config_dellanox_csm_1_2.py

- Fixed output of CANU validate
- Fixed Mellanox validate output
- Added a warning to tell users to utilize the checkpoint feature
- Added IP-Helper to CMN vlan
CASMNET-1092
CASMNET-996
CASMNET-1077
CASMNET-1098
Tested on:
VirtualEnv

CASMNET-1092

---

canu/utils/sls.py
readme.md

CASMINST-3485

---

network_modeling/configs/templates/1.0/dellmellanox/full/sw-spine.primary.j2
network_modeling/configs/templates/1.0/dellmellanox/full/sw-spine.secondary.j2
network_modeling/configs/templates/1.2/dellmellanox/full/sw-spine.primary.j2
network_modeling/configs/templates/1.2/dellmellanox/full/sw-spine.secondary.j2
readme.md
tests/test_generate_switch_config_dellanox_csm_1_0.py
tests/test_generate_switch_config_dellanox_csm_1_2.py

Fix mellanox web interface command.
CASMINST-3986
Tested on:
VirtualEnv

CASMINST-3986

---

canu/.version
canu/backup/network/network.py
readme.md

Description: What does this change do?  Use examples of new options and output changes when possible.  If other changes were made list these as well in a list.
* Resolves `CASMNET-1192`
* Relates to `N/A`
* Requires `N/A`
Tested on:
* Local

added folder check for Canu backup

---

canu/.version
canu/generate/switch/config/config.py
network_modeling/configs/templates/1.0/aruba/common/bmc.j2
network_modeling/configs/templates/1.0/dellmellanox/common/bmc.j2
network_modeling/configs/templates/1.2/aruba/common/bmc.j2
network_modeling/configs/templates/1.2/dellmellanox/common/bmc.j2
readme.md

Fix sw-hsn mgmt and pdu port config generation.
readme markdown lint... 
CASMNET-1356
virtualenv

CASMNET-1356

---

canu/utils/sls.py

Missed in PR 200 because of fork/merge model behavior of CI/CD were several nox lint test failures.  These are fixed here.
* Relates to CASMNET-1817

CASMNET-1817 Fix nox linting failures missed in previous PR

---

README.md
network_modeling/configs/templates/1.3/aruba/common/uan.j2

- Shutdown UAN CAN port when CHN is enabled.
CASMNET-1910
Tested on:
surtur

CASMNET-1910

---

README.md
canu/backup/network/network.py
canu/test/test.py
canu/utils/inventory.py

Fix sls_utils so that it works correctly when using a SLS.json file.
CASMNET-1912
Tested on:
Surtur, Drax

CASMNET-1912

---

.github/PULL_REQUEST_TEMPLATE.md
Jenkinsfile.github
Makefile
README.md

Description:
Various markdown adjustments/tweaks.
* Resolves: `Issue`
* Relates to: `Issue`
* Requires: `Issue`
Tested on:

Various markdown fixes

---

canu/report/network/version/version.py
canu/test/test.py
canu/utils/host_alive.py
docs/generate_network_config.md
docs/generate_switch_config.md
setup.py

Description:
bump library versions.
* Resolves: `Issue`
* Relates to: `Issue`
* Requires: `Issue`
Tested on:

bump lib versions

---

.gitignore
MANIFEST.in
setup.py

Fast-track https://github.com/Cray-HPE/canu/issues/237 into 1.6.27.

Fast-track #237 into 1.6.27.

---

Dockerfile
Jenkinsfile.github
Makefile
setup.py

- Relates to: MTL-1708
- RFE Pull Request
Continue to build and publish SP3 RPMs while publishing SP4 RPMs.
The SLES 15SP3 build creates an RPM with SP3 metadata and publishes it to `sle-15sp3`:
```bash
Name        : canu
Version     : 1.6.20~97~ga389a39
Release     : 1
Architecture: x86_64
Install Date: (not installed)
Group       : Unspecified
Size        : 51349236
License     : MIT License
Signature   : (none)
Source RPM  : canu-1.6.20~97~ga389a39-1.src.rpm
Build Date  : Fri 02 Dec 2022 09:54:05 PM UTC
Build Host  : 1b14ed2776f0
Relocations : (not relocatable)
Vendor      : Cray HPE
URL         : https://github.com/Cray-HPE/canu.git
Summary     : CSM Automatic Network Utility
Description :
Git Repository: canu
Git Branch: MTL-1708-SP4
Git Commit Revision: a389a391
Git Commit …
```

MTL-1708 Build SP3 and SP4

---

Dockerfile
Jenkinsfile.github
Makefile
setup.py

Description:
Pulls in build changes for publishing to SP3 and SP4 repos, as well as Python 3.10.8.
* Relates to: MTL-1708
Tested on:

Release 1.6.28

---

README.md
canu.spec
canu/inventory/__init__.py
canu/inventory/ansible.py
canu/inventory/plays/aruba-aoscx.yml
canu/utils/inventory.py
canu/utils/sls.py
canu/validate/network/cabling/cabling.py
canu/validate/paddle/paddle.py
canu/validate/shcd/shcd.py
network_modeling/NetworkModel.py
network_modeling/NetworkNode.py
pyinstaller.py
setup.py
tests/test_ansible.py
tests/test_validate_shcd.py

Description:
First payload of release 1.6.29.
* Resolves: `Issue`
* Relates to: `Issue`
* Requires: `Issue`
Tested on:

Release 1.6.29-1

---

.github/PULL_REQUEST_TEMPLATE.md

several checkboxes have been removed since they are automatically gating a PR from merging such as nox tests, linting, etc.
it also simplifies it a bit so the submitter has less text to manipulate in order to complete the form.
N/A

update the pull request template.

---

docs/templates/quickstart.md
docs/templates/venv.md
mkdocs.yml

Description:
Restores instructions for running canu in a virtualenv

restore virtualenv setup instructions

---

canu/generate/network/config/config.py
canu/generate/switch/config/config.py
canu/test/test.py
canu/utils/sls.py

Description:
Fixes some security hotspots including `http`-->`https` and setting `autoescape=True` or  `autoescape=select_autoescape()`
* Resolves: sonarcloud issues
Tested on:

fix sonarcloud security issues

---

Dockerfile
Makefile
canu/utils/sls.py

Addresses hadolint suggestions by fixing or disabling them inline.

address hadolint suggestions

---

canu/backup/network/network.py
canu/report/network/firmware/firmware.py
canu/report/switch/cabling/cabling.py
canu/send/command/command.py
canu/test/test.py
canu/validate/network/bgp/bgp.py
canu/validate/shcd_cabling/shcd_cabling.py

Fixes 13 remaining bugs identified on sonarcloud.
* Resolves: sonarcloud bugs
- checked that spinner still worked
- checked that colors worked
- `canu validate network bgp` on `#surtur`

fix remaining 13 sonarcloud bugs

---

canu/generate/switch/config/config.py
canu/validate/network/cabling/cabling.py
pyproject.toml

Shows dependabot who is boss by picking the right flake8 dependencies.
* Closes #308 
* Closes #300  
`nox -e lint`

Flaky friday

---

canu/generate/network/config/config.py
canu/generate/switch/config/config.py
canu/inventory/ansible.py
canu/report/network/cabling/cabling.py
canu/report/switch/cabling/cabling.py
canu/validate/network/bgp/bgp.py
canu/validate/shcd/shcd.py
network_modeling/NetworkNode.py

Fixes minor code smells detected by sonar cloud:
- remove redundant or useless `continue`s/`pass`es 
- use `\d` in regex instead of `[0-9]`

Minor smells

---

.github/dependabot.yml

Auto-updates the GitHub workflow plugins.

Periodically Update GitHub workflows

---

Jenkinsfile.github

Ignore builds from `dependabot/github_actions` branches, and remove unnecessary `labels`.

Cleanup agent labels and ignore certain branches

---

canu/test/test.py
canu/utils/inventory.py
canu/utils/sls_utils/Networks.py
canu/utils/sls_utils/ipam.py
canu/validate/paddle_cabling/paddle_cabling.py

- Fixes a lingering bug detected in sonar cloud.
- fixes several other Major code smells

Sonarcloud follow up

---

Jenkinsfile.github

RPMs won't sign correctly following the #355.

Fix RPM signing

---

pyproject.toml

surtur & fanta
canu test
canu validate shcd --shcd shcd.xlsx --tabs Mountain-Management,10_25_100G,NMN,HMN --corners K31,U52,K37,U80,J19,U20,J20,U37 -a TDS
canu report network cabling --ips 10.254.0.2,10.254.0.3,10.254.0.4
canu generate network config --ccj ./ccj.json --sls-file ./sls.json --csm 1.4 -a TDS --folder ./
canu validate switch config --ip 10.254.0.2 --generated ./sw-spine-001.cfg
canu validate network bgp --verbose

Library bumps

---

Jenkinsfile.github

- publish to 'noos' zypper repo
https://jira-pro.it.hpe.com:8443/browse/CASMINST-3431
RPM installed successfully. (no code changes)

CASMINST-3431 noos

---

network_modeling/configs/templates/1.5/aruba/common/acl.j2
network_modeling/configs/templates/1.5/dellmellanox/common/acl-mellanox.j2

Add ACL for HMN DHCP server.
CASMNET-2158
CAST-33571
surtur, fanta

CASMNET-2158 add dhcp hmn acl

---

.github/CHANGELOG.md
canu/generate/switch/config/config.py
network_modeling/configs/templates/1.5/aruba/common/acl.j2
network_modeling/configs/templates/1.6/aruba/common/acl.j2

update ACLs to apply to default vrf
Tested on Surtur.

CASMNET-2240 update ACLs to apply to default vrf

---

canu/config/network/network.py
canu/generate/switch/config/config.py
network_modeling/configs/templates/1.7/aruba/common/_acl_revert.j2
network_modeling/configs/templates/1.7/aruba/common/services_acl.j2
network_modeling/configs/templates/1.7/aruba/common/services_objects.j2
tests/data/golden_configs/individual_templates_1.7/services_acl.j2.cfg
tests/data/golden_configs/individual_templates_1.7/services_objects.j2.cfg

ACL Update nmn isolation
