Cray-HPE/canu

canu/generate/network/config/config.py

When generating configurations, different architectures typically expect some node/device types - UAN for example.  Absence of the expected type isn't necessarily an error, but CANU warns when some device types aren't found.  The warning was very confusing and this change attempts to provide better user guidance.
* Resolves CASMNET-895
Passed modified nox tests.

CASMNET-895: Fix confusing warning and user guidance in config generation.

---

network_modeling/models/cray-network-architecture.yaml

This adds PDUs as a hardware/architecture option.
It also adds more `lookup_names` for `slurm` and `nid` node types (both of which are used in `csi`.
This PR, along with #22 should close #15.

CASMNET-806: add PDU to to model/config

---

canu/validate/shcd_cabling/shcd_cabling.py
docs/validate_shcd_cabling.md
tests/test_validate_shcd_cabling.py

Signed-off-by: Jacob Salmela <jacob.salmela@hpe.com>
Adds a `--macs` flag to the `canu validate shcd-cabling` command, which prints off mac addresses needed for use with `csi config init`.
```
/  Connecting to 10.103.2.101 - Switch 10 of 10        
ncn-w001,ab:cd:ef:12:34:56
ncn-w002,ab:cd:ef:12:34:56
...
...
(.venv) jsalmela:~/git/canu (ncn_macs)$ 
```
* Relates to MTL-1556
Tested on:
* odin

MTL-1556 print ncn mac addresses for use with 'csi config shcd'

---

Dockerfile
readme.md

Include `jq` in the CANU docker environment so `sls_input_file.json` can be inspected and processed without having to break out of the container environment.
* Resolves `CASMNET-1056`
Tested on:
* Tested locally using a Linux VM.

CASMNET-1056 - Include jq in CANU docker image

---

readme.md
setup.py

Jinja2 configuration templates were moved down one level to accommodate CSM version differences.  The installer via setup.py was not changed to follow the new template locations.  This causes generation of configurations to fail in the 1.0.0 release. 
* Resolves CASMNET-1070
Tested on:
* Docker local.
* Python virtual environment.
* Pyinstaller binary.

CASMNET-1070: Modify setup.py file globs to use migrated Jinja2 templates

---

canu/.version
canu/validate/shcd/shcd.py
network_modeling/schema/paddle-schema.json
readme.md
tests/data/Full_Architecture_Golden_Config_1.1.5.json
tests/test_validate_paddle.py
tests/test_validate_paddle_cabling.py

Previously when a Paddle/CCJ file was created from a validated SHCD there was no way to reference which SHCD (or SHCD version more specifically) was used to create the CCJ file.  This change adds the originating SHCD filename to the CCJ JSON file.
* Resolves CASMNET-1188
Tested on:
* Fanta data

Track SHCD filename in paddle JSON.

---

canu/.version
canu/generate/network/config/config.py
canu/generate/switch/config/config.py
canu/validate/network/cabling/cabling.py
canu/validate/shcd/shcd.py
canu/validate/switch/config/config.py
network_modeling/NetworkNodeFactory.py
readme.md

Description: Allows canu to gracefully exit.
* Resolves CASMNET-1195
Tested on:
* Tested locally

CASMNET-1195 exit(1) bugfix

---

canu/.version
canu/generate/switch/config/config.py
canu/validate/switch/config/config.py
readme.md

Fix aruba banner output during `canu validate`
CASMNET-1346
virtual env/surtur

CASMNET-1346

---

Jenkinsfile.github
Makefile
Makefile_image

Only build and publish an RPM for one service pack, this'll shorten the build length. There's no functional difference in canu between SP2 and SP3 to require building for both.
Remove redundant instances of "canu". Replace manual cleanup of file permissions with the csm-shared-library.postChownFiles() function.
This will publish only a sles15sp3 RPM, meaning the CSM manifest will now need to:
- Cease including canu in https://github.com/Cray-HPE/csm/blob/main/rpm/cray/csm/sle-15sp2/index.yaml
- Will start needing to include canu in https://github.com/Cray-HPE/csm/blob/main/rpm/cray/csm/sle-15sp3/index.yaml

Cleanup Builds

---

Jenkinsfile.github

This just renames the `Jenkinsfile.github` variable "`pythonVer`" to "`pythonVersion`", making it match other repo's implementation of csm-docker-sle-* images.

expand spelling for consistency

---

.github/CODEOWNERS
Dockerfile

This switches the docker image to a new base image that has the same environment we use to build canu.

Use python docker image

---

README.md
canu/generate/network/config/config.py
canu/generate/switch/config/config.py
canu/validate/switch/config/aoscx_options.yaml
network_modeling/configs/templates/1.3/arista/sw-edge.primary.j2
network_modeling/configs/templates/1.3/arista/sw-edge.secondary.j2
tests/test_generate_switch_config_aruba_csm_1_2.py

- Update Arista BGP templates
- Add feature flag to select either CHN or CMN for BI-CAN BGP control plane traffic.
- Fix ordering of switch configuration when using custom switch configs.
CASMNET-1896
CAST-30648
CASMNET-1899
Tested on:
surtur

CASMNET-1896

---

Jenkinsfile.github
Makefile
canu.spec

#219 bypassed the RPM build check somehow, and now develop isn't building RPMs. The problem is `env.GIT_REPO_NAME` was renamed to `NAME` but the refactor was not fully complete.

Fix broken RPM build from #219

---

README.md
canu/cli.py
canu/generate/network/config/config.py
canu/generate/switch/config/config.py
canu/utils/cache.py
canu/validate/shcd/shcd.py
network_modeling/models/cray-network-architecture.yaml
tests/test_generate_switch_config_arista_csm_1_2.py
tests/test_generate_switch_config_aruba_csm_1_0.py
tests/test_generate_switch_config_aruba_csm_1_2.py
tests/test_generate_switch_config_dellanox_csm_1_0.py
tests/test_generate_switch_config_dellanox_csm_1_2.py

Description:
* KVM and GPU nodes have been in the v2 architectures fro a long time,  but were missing in the v1 architecture.  These node types have been added to the Dell and Mellanox v1 network architecture.
* Previously, during generation of switch and network configurations, spurious debug messages appeared from the network model and other libraries.  This made the output verbose and unclear.  A `--log` option has been added to `canu generate network config` and `canu generate switch config` and base logging initialized.  This change clears up default output.
* Moved helpful hint warnings about nodes often found on PoR systems but not found on existing system  to `--log WARNING`.  General user feedback were that this was either confusing or misleading.
* Rewrote warning text for …

Add missing nodes to v1 architecture and clean up switch and network config generation output.

---

setup.py

Dependabot would like to bump `pytest` from version 7.1.3 to 7.2.0.  Version 7.2.0 of `pytest` removed `py` from internal loading.  This change adds `py` as a testing dependency.
* Solution suggested here:  https://github.com/Teemu/pytest-sugar/issues/243
* Relates to: https://github.com/Cray-HPE/canu/pull/226

Add py dependency to to enable pytest version bump

---

Jenkinsfile.github
canu.spec

Description:
Stable builds of `canu` are reporting a version string with `dev1` appended to the end, this implies the build was done with a dirty repo (uncommitted changes). This occurs because the CSM metadata we add to the spec file causes the repo to become dirty. This change tells Git to assume that the `.spec` file is clean, thus preventing git from identifying the repo as dirty during the build.
For example, this build was from a stable 1.6.26 git-tag but it resulted in a version string of 1.6.26.dev1 (implying it is unstable and from a dirty repo).
```bash
redbull-ncn-m001-pit:~ # rpm -ivh https://artifactory.algol60.net/artifactory/csm-rpms/hpe/stable/sle-15sp2/canu/x86_64/canu-1.6.26-1.x86_64.rpm
Retrieving https://artifactory.algol60.net/artifactory/csm-rpms/hpe/stable/sle-15sp2/ …
```

Relates to #44 - Fixes stable RPM's

---

Dockerfile
Jenkinsfile.github

Description:
Stable Docker images (ones built from git-tags, previously from `main`) were failing due to the Zypper GPG checks. The GPG checks do not have the public key from our repository necessary for accepting signed RPMs.
This bypasses those checks, allowing stable Docker builds to work.
A test 1.6.26 tag was taken from this feature branch (which has been deleted and no longer exists), the test tag yielded a successful build: https://jenkins.algol60.net/job/Cray-HPE/job/canu/view/tags/job/1.6.26/7/console
* Relates to: #44 
Tested on:

Relates to #44 - Fix stable Docker images

---

Jenkinsfile.github
canu.spec

Minor `Jenkinsfile` and license updates. This simplifies some things in the `Jenkinsfile`, and conforms to my current template I'm using for several RPMs used in the PIT and NCN images.

Updating template for `Jenkinsfile`

---

setup.py

Description:
If Snyk scanning is ever added, then `setup.py` will be referred to in an isolated environment for dependnecy scanning that does not contain `PKG-INFO` (or `.git/` for that matter). Snyk will fail when invoking `get_version()` unless it reesolves the version from the already installed `canu` app.
This is a very minor follow-up to #234 .
* Resolves: `Issue`
* Relates to: `Issue`
* Requires: `Issue`
Tested on:

Minor update to support Snyk scanning

---

.gitignore
MANIFEST.in
setup.py

Description:
Fixes local dev environments including necessary data files when installing `canu`, where without the files certain commands will produce a traceback. This wasn't exhibited on a system with the `canu RPM installed because these data files were called out in `pyinstaller.py`, `pyinstaller.py` isn't invoked in local dev environments.
I verified this works by invoking commands locally and via a feature RPM install.
Local Install
```bash
canu, version 1.6.20.post95
canu validate shcd -a V1 --shcd Cray\ Inc-Shasta\ RiverSystemForServiceTraining_SHCD_RevA8.xlsx --tabs 40G_10G,NMN,HMN --corners J28,T54,J15,T31,J20,U58 --json
```
System/RPM Install:
```bash
redbull-ncn-m001-pit:/var/www/ephemeral/prep # canu --version
canu, version 1.6.20.post95 …
```

Fixes #237

---

README.md
canu.spec
canu/inventory/__init__.py
canu/inventory/ansible.py
canu/inventory/plays/aruba-aoscx.yml
canu/utils/inventory.py
canu/utils/sls.py
canu/validate/shcd/shcd.py
pyinstaller.py
setup.py
tests/test_ansible.py

Description:
- adds a standalone `canu-inventory` command for use with ansible (CASMNET-1968)
- adds a playbook (CASMNET-1982) that 
- validates a plain-text config
- creates a checkpoint from the running-config*
- uploads the new config to the switch and sets it as the running config
*this needed a slight workaround that changes the banner on the running-config.  Without that task, the play fails:
> 'GENERIC OPERATION ERROR: Checkpoint already exists in the database or it is a duplicate checkpoint'
* Resolves: `CASMNET-1968
* Resolves: `CASMNET-1982
Tested on:
- Local
- `#surtur`

CASMNET-1968 dynamic inventory

---

Jenkinsfile.github

Description:
Fixes Docker-in-Docker publishing; since a Docker container is used to provide `os-release` for determining where to publish the RPMs, the ClamAV `Docker` container needs `docker.sock` mounted so it can run Docker-in-Docker.
Additionally, the SSH public keys on the node are not available to the Docker container for sending RPMs to DST for signing. This mounts the SSH keys for the Docker container to successfully sign the RPM.

Stable Build Needs

---

README.md
canu/report/network/cabling/cabling.py
canu/report/switch/cabling/cabling.py
canu/report/switch/firmware/firmware.py
canu/utils/vendor.py
canu/validate/network/bgp/bgp.py
canu/validate/network/cabling/cabling.py
canu/validate/paddle_cabling/paddle_cabling.py
canu/validate/shcd/shcd.py
canu/validate/shcd_cabling/shcd_cabling.py
docs/network_configuration_and_upgrade/checks_and_validations.md
docs/templates/validate_network_config.md
docs/validate_network_config.md
tests/test_report_network_cabling.py
tests/test_report_switch_cabling.py
tests/test_report_switch_firmware.py
tests/test_validate_network_cabling.py
tests/test_validate_paddle_cabling.py
tests/test_validate_shcd_cabling.py

This bugfix addresses the following commands:
* `canu validate network cabling`
* `canu validate shcd-cabling`
* `canu validate paddle-cabling`
LLDP data is queried from the switches for these commands.  This data is then transformed into usable information both for reporting and entering into the CANU model.  Some times either LLDP is not running on the device connected to the switch or the LLDP information does not reduce to a singular physical port (in the case of bond0 for instance).  In these cases the port number was None in Python and while this is great for error checks in Python, loading None as a port number into the CANU model caused exceptions to be thrown.  The bugfix (CASMNET-2034) adds the detected node to the model where possible, but does not connect the node to the …

Better LLDP data checking and error handling

---

README.md

Fixes a broken docs link to the generate switch config details.

Fixed broken link to generate_switch_config.md

---

Dockerfile

The existing strict versions cause issues when an upstream update is pushed.  This commit fixes when it fails with a message like:
```
[2023-03-03T20:31:56.707Z] #8 0.884 ERROR: unable to select packages:
[2023-03-03T20:31:56.707Z] #8 0.920   git-2.38.4-r1:
[2023-03-03T20:31:56.707Z] #8 0.920     breaks: world[git=2.38.4-r0]
```
Description:
* Resolves: a broken Dockerfile
Tested on:

relax version pinning in the Dockerfile.  

---

.github/workflows/hadolint.yml
Dockerfile
Jenkinsfile.github
Makefile

Description:
This does a few things:
- Speeds up the Jenkins build, building the two Docker images in parallel before publishing them at the same time.
- Leveraged `PYTHON_VERSION` `ARG` in the `Dockerfile`, replacing occurances of `3.10` with `${PYTHON_VERSION}`
- `--build-arg` was not actually passing a value for `PYTHON_VERSION` and `ALPINE_IMAGE`, each `--build-arg` needed to be surrounded in single quotes
- Removed redundant definition of the alpine image in the `FROM`, now it is supplied by the fixed `--build-arg`
- Added Hadolint, a `Dockerfile` scanner that provides optimization and lint suggestions that will show up here: https://github.com/Cray-HPE/canu/security/code-scanning?query=
- Added `py3-wheel` to the `Dockerfile` to suppress warnings from `pip` when dependencies that …

Optimize Jenkins and Fix `--build-arg` in `Dockerfile`

---

.github/CHANGELOG.md
Dockerfile
canuctl
docs/templates/container_install.md

but does not quite fit our needs.  this makes it a bit easier for the end user to pull/build the necessary image.
Description:
- adds more contextual text to `-h`elp flag
- mounts `/etc/kubernetes` and sets `KUBECONFIG` for interactions with SLS
- breaks `canuctl` down into more functions
- uses global vars
- adds docs regarding `canuctl`
* Relates to #255 
* Fixes CASMNET-2074
* Relates to #200 
Tested on:
Local and `#surtur`

adjust canuctl script.  This was initially a port from an older branch,

---

.github/actions/prepare-artifacts/action.yml

This fixes the promotion workflow logic for waiting on artifacts.
The `jf` command does not return a non-zero return code if no artifacts are found, unless `--fail-no-op=true` is set. Since this argument was missing, the wait condition fails.

Relates to 288 - Fix return code

---

.github/actions/prepare-artifacts/action.yml
.github/workflows/promote-prerelease.yml
.github/workflows/promote-release.yml

There's a race condition when moving onto the `src` RPMs, in some cases the `src` and non-`src` RPMs publish ahead of one another and/or a few seconds apart. The workflow will try fetching `src.rpm`s before they're published. Add another wait before the `src` RPM move.
Also add another wait before downloading anything incase parallel builds are at play, they likely are finishing within seconds of each other.

288 Fix race condition

---

.github/CHANGELOG.md
Dockerfile
canuctl

- I neglected to adjust `canuctl` for the `ALPINE_IMAGE`/`ALPINE_VERSION` flow after yesterday's merges.  This allows the rebuilding of the image to work properly.
- only mounts `/etc/kubernetes` if it exists
* Introduced by: #310 
* Overlooked in: #305 
`canuctl -r -p` on `#surtur`

Canuctl rebuild

---

canu/report/network/cabling/cabling.py
canu/report/switch/cabling/cabling.py
canu/utils/heuristics.py
tests/test_report_network_cabling.py
tests/test_report_switch_cabling.py

Description:
Originally the `canu report switch cabling` and `canu report network cabling` commands used LLDP, ARP and MAC address table data from switches, with LLDP data being canonical.  This posed a problem when a device did not run LLDP or LLDP data didn't return anything particularly useful.
This change allows the addition of system metadata and "heuristics" of typical device use to annotate the LLDP data.  The following lookup data can be used and is listed in priority order:
- If Kea lease data is available it is used to match an LLDP MAC with a system hostname, then
- If SLS data is available it is used to match ARP IP data with a system hostname, then
- If SMD data is available it is used to match LLDP MAC addresses with a system hostname, then
- Heuristic lookups of the MAC are …

Add Kea, SLS, SMD and heuristic lookup tables to fill out LLDP data for cabling reports and validation

---

Dockerfile
Makefile
canuctl

- Adds ansible to the container by way of a new stage in the `Dockerfile`.
- Enables buildkit for capable machines to speed builds
- Reduces overall image size by disabling caching
- visually separates each stage in the `Dockerfile` for easier editing 
* Closes #253 
* Closes CASMNET-2077
* Relates to #265 
Built the prod container and ran an ansible play:
```
% ./canuctl -r -p 
canu ~/mounted$ ansible-playbook -i /opt/venv/bin/canu-inventory canu/inventory/plays/aruba-aoscx.yml -e config_folder=$PWD/netbak/ --limit sw-leaf-bmc-001
PLAY [aruba] ****************************************************************************************************************************************************************************************************************************
TASK [Gathering Facts] …
```

Bundle ansible in the container

---

Jenkinsfile.github

It is useful to have python 3.9 and 3.10 building in our GitHub actions, but as far as deliverables go our RPM installs a compiled binary and it doesn't need to ship different Python flavors.
Since our matrix of builds often has an Artifactory failure on one or the other, it would do us good to just build the RPM for _one_ Python flavor (thus reducing our matrix to one).
The matrix is staying, incase we do want to build for multiple Python versions again but also for enabling us to build canu for aarch64 if/when that time comes.

Stop building Py 3.9 RPMs and Docker Images

---

.dockerignore
Dockerfile
Jenkinsfile.github
Makefile
canuctl

This PR does a few build related things:
- Per @mtupitsyn's directions, this modifies our `Jenkinsfile` to lighten the load on Jenkins. Presently we request multiple hosts and run one Docker container on each of those hosts, this puts a high-demand on Jenkins. Now only one host is requested, and then the matrix of builds (as well as the Docker builds) all run on that single host.
- The Docker image now has multi-arch support by switching to use the `docker buildx build` system. Now the published image tags support the  linux/arm64 and linux/amd64 platforms. When building images, users can override this multi-arch by setting `PLATFORMS=linux/amd64` or `PLATFORMS=linux/arm64` in their environment
- `make *_image` commands in the `Makefile` are all consolidated to a single `make image_$` …

Optimize Jenkins, Build multi-arch Docker Image, and Tidy `Makefile`

---

canu.spec

Invoke `canu --version` before finishing the RPM build to make sure the built binary even starts up. Prevent the need for #354 ever happening again.

Check `canu`'s built binary works before merging

---

.github/dependabot.yml

`canu` has so many dependencies that going through only 5 weekly will never get us caught up. If we go through 10 weekly (the maximum dependabot will manage) then we can catch up faster.

Allow up to 10 dependency PRs

---

.github/CHANGELOG.md
pyinstaller.py

- Add 1.5 dellanox templates
- Add missing aruba 1.5 templates
CASMNET-2146

CASMNET-2146 add 1.5 dellanox, fix aruba templates

---

.github/CHANGELOG.md
canu/validate/network/bgp/bgp.py
tests/test_validate_network_bgp.py

- Fix CANU exit code on BGP validation
CASMNET-2017
surtur
fanta
```
ncn-m001:~/lbates # canu validate network bgp
Password:
|  Connecting
BGP Neighbors Established
--------------------------------------------------
FAIL - IP: 10.254.0.2 Hostname: sw-spine-001
PASS - IP: 10.254.0.3 Hostname: sw-spine-002
Errors
--------------------------------------------------
10.252.1.100    - Idle
ncn-m001:~/lbates # echo $?
1
```

CASMNET-2017 Fix CANU exit code on BGP validation 

---

.github/CHANGELOG.md
canu/validate/shcd_cabling/shcd_cabling.py

* Resolves: CASMTRIAGE-6179
Checks for errors earlier (immediately after trying to connect to switches) and exiting if any are detected.
Ran the same command from the ticket and validated the output on bad credentials
```
~ # canu validate shcd-cabling --ips 10.252.0.2,10.252.0.3 --tabs 25G_10G --corners I14,Q51 --csm 1.5 -a TDS --shcd SHCD.xlsx
Password: 
Connecting to 127.0.0.6 - Switch 2 of 2         
====================================================================================================
Errors
====================================================================================================
10.252.0.2       - Timeout error connecting to 10.252.0.2. Check the IP address or credentials and try again.
10.252.0.3       - Timeout error connecting to 10.252.0.3. Check the IP …
```

CASMTRIAGE-6179 fix exception on invalid password with shcd cabling

---

network_modeling/configs/templates/1.5/aruba/full/sw-leaf-bmc.j2
network_modeling/configs/templates/1.5/aruba/tds/sw-leaf-bmc.j2

Update CSM 1.5 Aruba templates to add the SNMP server to the CSM VRF in order to allow hms-discovery and REDS to function correctly.
* Resolves: [CASMTRIAGE-6517](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6517)
Generated configuration using input files from tyr.
```
$ canu generate network config --csm 1.5 -a TDS --ccj ccj.json --sls-file tyr_sls.json --folder output
sw-spine-001 Config Generated
sw-spine-002 Config Generated
sw-leaf-bmc-001 Config Generated
```
Verified output was as expected.
```
$ grep snmp-server output/sw-leaf-bmc-001.cfg
snmp-server vrf default
snmp-server vrf CSM
```

CASMTRIAGE-6517 - Add snmp-server to the CSM VRF on leaf-bmc devices

---

.github/CHANGELOG.md
canu/generate/switch/config/config.py

When CDU switches are listed (created) prior to Spine switches in either an SHCD, the resulting Paddle (CCJ) also contains this ordering.  When an SHCD or CCJ of this type is used to generate CDU switch configurations the code enters into a little used path (typically spines are created prior to cdus).  This path did not completely initialize a variable checking whether the switch is primary in a pair, resulting in an exception.
This change cleans up the code path to fully initialize the variable and avoid exceptions.
* Resolves: [CASMTRIAGE-6641](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6641)
The customer file which illustrated the problem and exception was re-run with the code change without error.

Fix selection of primary switch in little used code path

---

pyinstaller.py

Add 1.6 template files to pyinstaller.
This is needed to make the RPM functional.

Fix 1.6 pyinstaller

---

.github/CHANGELOG.md
canu.spec

Sets the canu user's login shell to `/sbin/nologin`
* Relates to: CAST-36209
* Resolves CASMINST-6904
tested with an older canu version installed
```
ncn-m001:~ # canu --version
canu, version 1.7.6
ncn-m001:~ # getent passwd canu
canu:x:1000:1000:CANU user:/home/canu:/bin/bash
ncn-m001:~ # ls -l /usr/bin/canu*
-rwxr-xr-x 1 canu canu 44546496 Jun 25 10:23 /usr/bin/canu
-rwxr-xr-x 1 canu canu     6702 Jun 25 10:23 /usr/bin/canuctl
-rwxr-xr-x 1 canu canu 44543352 Jun 25 10:23 /usr/bin/canu-inventory
ncn-m001:~ # zypper in --allow-unsigned-rpm ./canu-1.8.2.dev3+gf28a0c4-1.x86_64.rpm
Loading repository data...
Reading installed packages...
Resolving package dependencies...
The following package is going to be upgraded:
canu
The following package has no support information from its vendor:
canu …
```

CAST-36209/CASMINST-6904 remove canu user and change ownership of canu-owned files

---

.github/CHANGELOG.md
canu/validate/network/cabling/cabling.py
tests/test_validate_shcd_cabling_format_dst_name.py

validate shcd-cabling'
When running 'canu validate shcd-cabling' with an SHCD that does not follow currently-supported naming conventions can cause this stacktrace:
```
File "cli.py", line 314, in <module>
File "click/core.py", line 1130, in __call__
File "click/core.py", line 1055, in main
File "click/core.py", line 1657, in invoke
File "click/core.py", line 1657, in invoke
File "click/core.py", line 1404, in invoke
File "click/core.py", line 760, in invoke
File "click/decorators.py", line 26, in new_func
File "validate/shcd_cabling/shcd_cabling.py", line 286, in shcd_cabling
File "validate/network/cabling/cabling.py", line 412, in node_model_from_canu
IndexError: list index out of range
[48583] Failed to execute script 'cli' due to unhandled exception!
```
canu is currently not setup to …

CASMTRIAGE-6650 fix and test for 'IndexError: list index out of range' with 'canu

---

pyproject.toml

Includes:
- https://github.com/Cray-HPE/canu/pull/481
- https://github.com/Cray-HPE/canu/pull/499
- https://github.com/Cray-HPE/canu/pull/514
- https://github.com/Cray-HPE/canu/pull/520
Tested on redbull by running the following commands and verifying their output and generated files:
```bash
canu validate shcd -a tds --shcd ./Shasta\ River\ Redbull\ CCD_RevA16.xlsx --tabs 25G_10G,NMN,HMN --corners I15,Q50,I9,S10,I20,S30 --log DEBUG --json --out ccj.json
ll
canu generate network config --ccj ccj.json --csm 1.6 --sls-file redbull/sls_input_file.json --folder generated
canu validate switch config --ip 10.254.0.2 --generated ./generated/sw-spine-001.cfg --remediation
```

One dep pr to rule them all part3

---

.github/dependabot.yml

Let's blaze through the backlog of updates by changing dependabot to "daily" for a short period of time, at least until we catch-up.

Speed up dependabot

---

network_modeling/configs/templates/1.5/aruba/common/mtn_hmn_vlan.j2
network_modeling/configs/templates/1.5/aruba/common/mtn_nmn_vlan.j2
network_modeling/configs/templates/1.6/aruba/common/mtn_hmn_vlan.j2
network_modeling/configs/templates/1.6/aruba/common/mtn_nmn_vlan.j2

Mountain HMN and NMN are now in custom VRF, this change implies using ospf area 2
Canu version 1.8 change Management Networks VRF from default to CSM, ospf area are also changed, this change hasn't been
applied to all NMN/HMN Vlans resulting in Mountain HMN/HMN still being in ospf area 1
the result is one ospf in area 1 for default vrf and two ospf areas (1 and 2) in CSM vrf, this patch fixes the discrepancy
addresses CAST-37220
Tested by applying the config to Hill CDU switches

CASMNET-2260 Mountain HMN and HMN should use ospf area 2

---

pyproject.toml

Includes:
- https://github.com/Cray-HPE/canu/pull/578
- https://github.com/Cray-HPE/canu/pull/577
- https://github.com/Cray-HPE/canu/pull/575
```bash
redbull-pit:/var/www/ephemeral/prep # canu --version
canu, version 1.9.6.dev58+g2fa613f
```
```bash
canu validate shcd -a tds --shcd ./Shasta\ River\ Redbull\ CCD_RevA16.xlsx --tabs 25G_10G,NMN,HMN --corners I15,Q50,I9,S10,I20,S30 --log DEBUG --json --out ccj.json
canu generate network config --ccj ccj.json --csm 1.6 --sls-file redbull/sls_input_file.json --folder generated
canu validate switch config --ip 10.254.0.2 --generated ./generated/sw-spine-001.cfg --remediation
```
Collected input and output files:
[canu-pr-579.tar.gz](https://github.com/user-attachments/files/18043492/canu-pr-579.tar.gz)

One dep pr to rule them all part8

---

.github/CHANGELOG.md
network_modeling/configs/templates/1.5/aruba/common/acl.j2
network_modeling/configs/templates/1.6/aruba/common/acl.j2

Add the CMN to the `mgmt` access list to permit SSH, HTTPS, and SNMP over the CMN.
* Resolves: `[CASMNET-2273](https://jira-pro.it.hpe.com:8443/browse/CASMNET-2273)`
Generated new configuration using data from hela, verified the CMN is now present in the access list.
```
$ diff orig/sw-spine-001.cfg new/sw-spine-001.cfg
7c7
< # CANU version: 1.9.6.dev59+gd3b6bc3
---
> # CANU version: 1.9.6.dev59+gd3b6bc3.d20250106
30,39c30,43
<     60 comment ALLOW SNMP FROM HMN METALLB SUBNET
<     70 permit udp 10.94.100.0/255.255.255.0 any eq snmp
<     80 permit udp 10.94.100.0/255.255.255.0 any eq snmp-trap
<     90 comment BLOCK SSH, HTTPS, AND SNMP FROM EVERYWHERE ELSE
<     100 deny tcp any any eq ssh
<     110 deny tcp any any eq https
<     120 deny udp any any eq snmp
<     130 deny udp any any …
```

CASMNET-2273 - CMN missing from mgmt access control list

---

canu/test/aruba/bgp_test.py
canu/test/aruba/test_suite.yaml
canu/test/aruba/vlan_interface_test.py
canu/test/test.py

This PR fixes the key error observed while running BGP tests by adding customized VRF name
https://jira-pro.it.hpe.com:8443/browse/CASMNET-2309
Tested on surtur spine switch

CASMNET-2309-fixed BGP tests

---

.github/CHANGELOG.md
canu/validate/shcd/shcd.py
network_modeling/schema/paddle-schema.json
tests/data/Full_Architecture_Golden_Config_1.1.5.with_shcd_metadata.json
tests/test_validate_paddle.py

A CCJ/paddle file includes information to reconstitute the topology of a management network.  Previously the originating SHCD and the CANU version were added to the CCJ metadata as convenience information to human users.  This change adds the tabs and corners and edge router information used in generating the CCJ. This information is optional, but helpful when one looks at a CCJ after much time has passed.
* Resolves: `CASMNET-2317`
- Tested with Creek internal system data.

CASMNET-2317 - Add validate shcd corners and tabs to CCJ metadata

---

pyinstaller.py

The CSM 1.7 templates has been to the pyinstaller.py file similar to how they have been for CSM 1.6 in this fix. 
https://jira-pro.it.hpe.com:8443/browse/CASMNET-2332

CASMNET-2332-adding csm 1.7 templates

---

canu/utils/sls_utils/Networks.py
tests/test_sls_utils_networks.py

Previously SLS Utils read in the system default route, but didn't allow official get and set off the value.  This changes adds access to the `system_default_route`.
* Resolves: `CASMNET-2319`
* Nox test added here.

CASMNET-2319 - Allow retrieval and setting of system default route.

---

canu/utils/sls_utils/schemas/sls_networks_schema.json

Since the beginning CSI has created SLS data that has a maximum VLAN range value of 4095.  The actual max physically allowed in networking is 4094 and CANU checked to enforce this physical value.
This change increases the max allowed VLAN to 4095 to match CSI. Many, many running systems have the 4095 data, but CANU is the only tooling that actually takes SLS network data and produces running switch configurations.  This change is not a runtime risk as it only impacts the VLAN range value in SLS which is not used by any tooling (including CANU).
No testing needed.  This only affects SLS VlanRange values which are not used by any tooling whatsoever.

CASMNET-2339 - Bump VLAN max in schema checks to 4095

---

canu/test/aruba/bgp_test.py
canu/test/aruba/services_acl_test.py
canu/test/aruba/test_suite.yaml
canu/test/aruba/vlan_interface_test.py
canu/test/test.py

This change adds tests to verify if the required services ACLs are present on spine, leaf switches by comparing it with the Services ACLs templates. 
https://jira-pro.it.hpe.com:8443/browse/CASMNET-2290
Tested on internal systems

Added tests for services ACL

---

canu/config/network/network.py
canu/generate/switch/config/config.py
network_modeling/configs/templates/1.7/aruba/common/_acl_revert.j2
network_modeling/configs/templates/1.7/aruba/common/services_acl.j2
network_modeling/configs/templates/1.7/aruba/common/services_objects.j2
tests/data/golden_configs/individual_templates_1.7/services_acl.j2.cfg
tests/data/golden_configs/individual_templates_1.7/services_objects.j2.cfg

Add NCN MTL ips to the NCN object group.  This allows the NCNS to talk to each other on both their NMN and MTL IPs without any restrictions.  Required for booting from the pit.
* Resolves: `CASMNET-2354`
Tested on surtur

CASMNET-2354: Add MTL NCN IPs to ACLs

---

canu/report/switch/firmware/firmware.py
tests/test_report_switch_firmware.py

The removal of the canu cache code in https://github.com/Cray-HPE/canu/pull/688 broke firmware version reporting for Mellanox devices because the commands used to gather the data were changed and the output processing doesn't work.
```
ncn-m001:~ # canu report switch firmware --csm 1.7 --ip 10.254.0.2 --password $SW_PASSWD
Traceback (most recent call last):
File "cli.py", line 289, in <module>
File "click/core.py", line 1161, in __call__
File "click/core.py", line 1082, in main
File "click/core.py", line 1697, in invoke
File "click/core.py", line 1697, in invoke
File "click/core.py", line 1697, in invoke
File "click/core.py", line 1443, in invoke
File "click/core.py", line 788, in invoke
File "click/decorators.py", line 33, in new_func
File "report/switch/firmware/firmware.py", line 146, …
```

CASMTRIAGE-8566 - canu report switch firmware fails for Mellanox
